// This is an autogenerated file from Firebase Studio.
'use server';

/**
 * @fileOverview An AI assistant that matches eDNA sequences against a database of known species.
 *
 * - matchEdnaSequence - A function that handles the eDNA sequence matching process.
 * - MatchEdnaSequenceInput - The input type for the matchEdnaSequence function.
 * - MatchEdnaSequenceOutput - The return type for the matchEdnaSequence function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const MatchEdnaSequenceInputSchema = z.object({
  ednaSequence: z
    .string()
    .describe('The eDNA sequence to match against known species.'),
  speciesDatabaseDescription: z.string().describe('The description of the species database.'),
});
export type MatchEdnaSequenceInput = z.infer<typeof MatchEdnaSequenceInputSchema>;

const MatchEdnaSequenceOutputSchema = z.object({
  speciesMatches: z
    .array(z.string())
    .describe('An array of species that match the eDNA sequence. If no matches are found, this will be an empty array.'),
  confidenceScores: z
    .array(z.number())
    .describe('An array of confidence scores for each species match. If no matches are found, this will be an empty array.'),
});
export type MatchEdnaSequenceOutput = z.infer<typeof MatchEdnaSequenceOutputSchema>;

export async function matchEdnaSequence(input: MatchEdnaSequenceInput): Promise<MatchEdnaSequenceOutput> {
  return matchEdnaSequenceFlow(input);
}

const prompt = ai.definePrompt({
  name: 'matchEdnaSequencePrompt',
  input: {schema: MatchEdnaSequenceInputSchema},
  output: {schema: MatchEdnaSequenceOutputSchema},
  prompt: `You are an expert marine biologist analyzing environmental DNA (eDNA) samples.

You have been given a genetic sequence and a description of the ecosystem from which it was collected.

Your task is to generate a list of plausible, hypothetical species that might correspond to this eDNA sequence, along with a confidence score for each match. The confidence score should be a number between 0 and 1.

The species should be relevant to the described ecosystem.

eDNA Sequence: {{{ednaSequence}}}
Ecosystem Description: {{{speciesDatabaseDescription}}}

Generate a few potential matches (e.g., 3 to 5 species).

Format the output as a JSON object with 'speciesMatches' and 'confidenceScores' arrays.
`,
});

const matchEdnaSequenceFlow = ai.defineFlow(
  {
    name: 'matchEdnaSequenceFlow',
    inputSchema: MatchEdnaSequenceInputSchema,
    outputSchema: MatchEdnaSequenceOutputSchema,
  },
  async input => {
    const {output} = await prompt(input);
    return output!;
  }
);
